export const CONTRACT_KEY = {
  CONNECTO_TOKEN: "CONNECTO_TOKEN",
  CONNECTO_PROTOCOL: "CONNECTO_PROTOCOL",
  CONNECTO_PROTOCOL_IMPL: "CONNECTO_PROTOCOL_IMPL",
  CONNECTO_NFT_MANAGER: "CONNECTO_NFT_MANAGER",
}
